---
- shell: java -version
  register: thisjava
  failed_when: false
  changed_when: false
- include_role: {name: corpusops.roles/localsettings_jdk}
  when: thisjava.rc != 0 and '1.8' not in thisjava.stderr
  tags: [jdk_install]
- file:
    state: directory
    path: "{{geoserver_vars.proot}}"
  tags: [jdk_jai]
- include_role: {name: corpusops.roles/install_archive}
  with_items: "{{geoserver_vars.jai}}"
  loop_control: {loop_var: _archive}
  tags: [jdk_jai]
- shell: |
    set -ex
    cd "{{geoserver_vars.proot}}/jai"
    if [ ! -e  "{{geoserver_vars.java_home}}/lib/ext" ];then
      mkdir -pv "{{geoserver_vars.java_home}}/lib/ext"
    fi
    cp -f lib/*jar "{{geoserver_vars.java_home}}/jre/lib/amd64"
    cp -f lib/*jar "{{geoserver_vars.java_home}}/lib/amd64"
    cp -f lib/*so  "{{geoserver_vars.java_home}}/jre/lib/ext"
    cp -f lib/*so  "{{geoserver_vars.java_home}}/lib/ext"
  tags: [jdk_jai]
  changed_when: false
