---
- shell: java -version
  register: thisjava
  failed_when: false
  changed_when: false
- include_role: {name: corpusops.roles/localsettings_jdk}
  when: thisjava.rc != 0 and '1.8' not in thisjava.stderr
  tags: [jdk_install]
- file:
    state: directory
    path: "{{item}}"
  loop: ["{{geoserver_vars.proot}}"]
  tags: [jdk]
- include_role: {name: corpusops.roles/install_archive}
  loop: "{{geoserver_vars.jai}}"
  loop_control: {loop_var: _archive}
  tags: [jdk_jai]
- shell: |
    set -ex
    cd "{{geoserver_vars.proot}}/jai"
    if [ ! -e  "{{geoserver_vars.java_home}}/lib/ext" ];then
      mkdir -pv "{{geoserver_vars.java_home}}/lib/ext"
    fi
    cp -f lib/*so "{{geoserver_vars.java_home}}/jre/lib/amd64"
    cp -f lib/*so "{{geoserver_vars.java_home}}/lib/amd64"
    cp -f lib/*jar  "{{geoserver_vars.java_home}}/jre/lib/ext"
    cp -f lib/*jar  "{{geoserver_vars.java_home}}/lib/ext"
  tags: [jdk_jai]
  changed_when: false
- name: archives
  get_url:
    url: "{{geoserver_vars.jce}}"
    checksum: "sha256:{{geoserver_shas['jce-'+geoserver_jce_version].dist}}"
    headers: "{{geoserver_vars.jce_headers}}"
    dest: "{{geoserver_vars.proot}}/{{geoserver_vars.jce|copsf_basename}}"
    mode: "0644"
  tags: [jdk_jce]
- name: "test if alreagy java unpacked"
  stat: {path: "{{geoserver_vars.proot}}/UnlimitedJCEPolicyJDK8/local_policy.jar"}
  failed_when: false
  register: _geoserver_jce_t
  tags: [jdk_jce]
- name: unarchives
  when: not _geoserver_jce_t.stat.exists
  unarchive:
    remote_src: true
    keep_newer: true
    src: "{{geoserver_vars.proot}}/{{geoserver_vars.jce|copsf_basename}}"
    dest: "{{geoserver_vars.proot}}"
  tags: [jdk_jce]
- copy:
    src: "{{geoserver_vars.proot}}/UnlimitedJCEPolicyJDK8/{{item}}"
    dest: "{{geoserver_vars.java_home}}/jre/lib/security"
    remote_src: true
    force: true
  loop: [local_policy.jar, US_export_policy.jar]
  tags: [jdk_jce]
- copy:
    src: "{{geoserver_vars.proot}}/UnlimitedJCEPolicyJDK8/{{item}}"
    dest: "{{geoserver_vars.java_home}}/lib/security"
    remote_src: true
    force: true
  loop: [local_policy.jar, US_export_policy.jar]
  tags: [jdk_jce]
