---
- block:
  - register: cops_configs_templatesl
    debug:
       msg: |-
        {% set res = [] %}
        {%  set _ = res.append({
          'name': "/etc/{0}/tomcat-users.xml".format(geoserver_vars.tomcat),
          'mode': "0644",
          'owner': "root",
          'group': "root",
          'template': '../templates/etc/tomcat/server.xml',
          }) %}
        {%  set _ = res.append({
          'name': "/etc/{0}/tomcat-users.xml".format(geoserver_vars.tomcat),
          'mode': "0644",
          'owner': "root",
          'group': "root",
          'template': '../templates/etc/tomcat/tomcat-users.xml',
          }) %}
        {%  set _ = res.append({
          'name': "/etc/default/{0}".format(geoserver_vars.tomcat),
          'mode': "0644",
          'owner': "root",
          'group': "root",
          'template': '../templates/default/tomcat',
          }) %}
        {{ res | to_json }}
    cops_configs_templates: "{{cops_configs_templatesl.msg}}"
  - include_role: {name: corpusops.roles/configs, private: true}
    vars:
      cops_configs_files: []
      cops_configs_copys: []
      cops_configs_templates: "{{cops_configs_templatesl.msg}}"
- cops_service:
    name: "{{geoserver_vars.tomcat}}"
    state: restarted

