---
# THIS SHOULD RESIDE IN AN ENCRYPTED VAULT
cops_deploy_ssh_key_paths:
  production:
    path: "{{'local/.ssh/deploy_production'|copsf_abspath}}"
    pub: |-
      ssh-rsa AAAAxxx== myapp@production
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      yyy==
      -----END RSA PRIVATE KEY-----
geoserver_password: "xxx"
geoserver_tomcat_users:
  - username: admin
    password: zzz
    roles: [tomcat]
