all:
  hosts:
    localhost:
      ansible_connection: local
    production-myapp.foo.net:
      sudo_flags: "-HE"
      ansible_port: 22
      ansible_user: root
      ansible_ssh_common_args: "-i {{cops_deploy_ssh_key_paths['production'].path}}"
geoserver_servers:
  hosts:
    production-myapp.foo.net:
app_servers:
  children:
    geoserver_servers:
controller:
  hosts:
    localhost:
