---
- shell:
    set -ex
    res=$(dirname $(dpkg -L gdal-data|grep wkt|head -n1))
    if [ "x$res" = "x" ];then res="{{geoserver_vars.gdal_data}}";fi
    echo $res
  register: _geoserver_gdal
- block:
  - register: cops_configs_filesl
    debug:
       msg: |-
        {% set res = [
        {'name': geoserver_vars.data,
         'mode': "0755",
         'owner': geoserver_vars.tomcat,
         'group': geoserver_vars.tomcat,
         'state': 'directory'},
        ] %}
        {{ res | to_json }}
  - register: cops_configs_templatesl
    debug:
       msg: |-
        {% set res = [
        {'name': "{0}/WEB-INF/web.xml".format(geoserver_vars.home),
         'mode': "0644",
         'owner': "root",
         'group': "root",
         'template': '../templates/webapp/WEB-INF/web.xml'},
        {'name': "{0}/conf/server.xml".format(geoserver_vars.tomcat_path),
         'mode': "0640",
         'owner': "root",
         'group': geoserver_vars.tomcat,
         'template': '../templates/tomcat/server.xml'},
        {'name': "{0}/conf/tomcat-users.xml".format(geoserver_vars.tomcat_path),
         'mode': "0640",
         'owner': "root",
         'group': geoserver_vars.tomcat,
         'template': '../templates/tomcat/tomcat-users.xml'},
        {'name': "/etc/cron.d/restart_tomcat",
         'mode': "0644",
         'owner': "root",
         'group': "root",
         'template': '../templates/cron'},
        {'name': "{0}/restart_tomcat.sh".format(geoserver_vars.data),
         'mode': "0755",
         'owner': "root",
         'group': "root",
         'template': '../templates/restart_tomcat.sh'},
        {'name': "/etc/systemd/system/{0}.service".format(geoserver_vars.tomcat_service),
         'mode': "0755",
         'owner': "root",
         'group': "root",
         'template': '../templates/etc/systemd/system/tomcat.service'},
        {'name': "/etc/logrotate.d/{0}".format(geoserver_vars.tomcat_service),
         'mode': "0644",
         'owner': "root",
         'group': "root",
         'template': '../templates/etc/logrotate.d/tomcat'},
        {'name': "/etc/default/{0}".format(geoserver_vars.tomcat_service),
         'mode': "0644",
         'owner': "root",
         'group': "root",
         'template': '../templates/etc/default/tomcat'},
        ] %}
        {{ res | to_json }}
  - include_role: {name: corpusops.roles/configs}
    vars:
      cops_configs_copys: []
      cops_configs_files: "{{cops_configs_filesl.msg}}"
      cops_configs_templates: "{{cops_configs_templatesl.msg}}"
- shell: |-
    set -ex
    cd "{{geoserver_vars.tomcat_path}}"
    chmod 751 .
    find temp/ work/ logs/ bin lib conf temp webapps|xargs chown {{geoserver_vars.tomcat}}:{{geoserver_vars.tomcat}}
  changed_when: false
- cops_service:
    daemon_reload: true
    name: "{{geoserver_vars.tomcat_service}}"
    state: restarted
    enabled: true
