---
geoserver_prefix: "/srv/projects/geoserver"
geoserver_proxy_timeout: "1200"
geoserver_proot: "{{geoserver_prefix}}/project"
geoserver_data: "{{geoserver_prefix}}/data/geoserver"
geoserver_restart_periodicity: "*/3 * * * *"
geoserver_name: geoserver
geoserver_cops_sub_namespaces:
  nginx: {}
geoserver_tomcat_ver: 8.5.30
geoserver_tomcat_sha: "{{geoserver_shas['tomcat-{0}'.format(geoserver_tomcat_ver)]}}"
# geoserver_version: "2.13.0"
geoserver_version: "2.12.3"
geoserver_sha: "{{geoserver_shas[geoserver_version].dist}}"
geoserver_plugin_gdal_sha: "{{geoserver_shas[geoserver_version].gdal}}"
geoserver_plugin_pyramid_sha: "{{geoserver_shas[geoserver_version].pyramid}}"
geoserver_shas:
  2.12.3:
    dist: eba9ee162f112fc81bbcf71103156e4ea9e4ecfaf5812683c121af1e6055f476
    gdal: d1b9e1d60a928637fdb65d1f036493e9ecc8816af57cb92a61cedad83dcce468
    pyramid: e6b02b751322dbb511c375c62d007d633bf321a1aae22a100dfc59159cff22ab
  2.13.0:
    dist: 368f5a14ed7a151a6920800ab4af38ef1e574e51de41549951ad76c447269679
    gdal: e77bc08af218eaca7dc3171be5b847f5431f0622ebafdb86002ab6a385dca717
    pyramid: 76aec9d6fb3fc1c9b70d21bc30a85a87edfe7eaac899bb140efbcef61378ffeb
  tomcat-8.5.30: ad2dc76d583397635a8c4bf765636bab283366af2f48b6d82107a5af29139d8c
  marlin-0.9.1:
    sun: "sha256:80c4325bfe2aa93df617bb763e3c090331ebb6badfd1caec778e8b8229aebcb3"
    dist: "sha256:94794c9964472a1c296c2ba400dfd2e9b7479ba36e4d00d2f20a37ad7827c3dd"
geoserver_marlin_ver: 0.9.1
geoserver_marlin:
- url: "https://github.com/bourgesl/marlin-renderer/releases/download/v0_9_1/marlin-{{vars['geoserver_marlin_ver']}}-Unsafe-sun-java2d.jar"
  checksum: "{{geoserver_shas['marlin-{0}'.format(geoserver_marlin_ver)].sun}}"
- url: "https://github.com/bourgesl/marlin-renderer/releases/download/v0_9_1/marlin-{{vars['geoserver_marlin_ver']}}-Unsafe.jar"
  checksum: "{{geoserver_shas['marlin-{0}'.format(geoserver_marlin_ver)].dist}}"
geoserver_home: "{{geoserver_tomcat_path}}/webapps/geoserver"
geoserver_todos:
- "http://docs.geoserver.org/latest/en/user/production/container.html#enable-the-marlin-rasterizer"
- "http://docs.geoserver.org/latest/en/user/production/container.html#enable-cors"
geoserver_java_xmx: 2048M
geoserver_java_xms: 256m
geoserver_java_opts: >
  -Dfile.encoding=UTF-8
  -Djava.library.path=/usr/lib/jni:/usr/lib/jvm/java-8-oracle/jre/lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
  -XX:SoftRefLRUPolicyMSPerMB=36000
  -Djava.awt.headless=true
  -DGEOSERVER_DATA_DIR={{geoserver_data}}
  -XX:+UseG1GC
  -Xmx{{geoserver_java_xmx}}
  -Xms{{geoserver_java_xms}}
  -Xbootclasspath/p:"{{geoserver_home}}/WEB-INF/lib/marlin-{{geoserver_marlin_ver}}-Unsafe.jar"
  -Dsun.java2d.renderer=org.marlin.pisces.PiscesRenderingEngine
#  --XX:+UseParNewGC
#  -XX:+UseParallelGC
#  -XX:+UseConcMarkSweepGC
geoserver_packages:
  - gdal-bin
  - libgdal-java
  - apache2-utils
  - python-passlib
  - python3-passlib
  - "{%- if (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '14.04'|copsf_looseversion) -%}
    libgdal1h
    {%- elif (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '16.04'|copsf_looseversion) -%}
    libgdal1i
    {%- else -%}
    libgdal20
    {%- endif -%}"
  - geoip-bin
  - "{%- if (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '14.04'|copsf_looseversion) -%}
    libgeos-c1
    {%- elif (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '16.04'|copsf_looseversion) -%}
    libgeos-c1v5
    {%- else -%}
    libgeos-c1v5
    {%- endif -%}"
  - "{%- if (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '14.04'|copsf_looseversion) -%}
    libgeos-3.4.2
    {%- elif (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '16.04'|copsf_looseversion) -%}
    libgeos-3.5.0
    {%- else -%}
    libgeos-3.6.2
    {%- endif -%}"
  - "{%- if (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <
          '14.04'|copsf_looseversion) -%}
    libgeoip
    {%- else -%}
    libgeoip1
    {%- endif -%}"
  # installed manually
  # - "{{geoserver_tomcat}}"
geoserver_tomcat: "{%- if (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '14.04'|copsf_looseversion) -%}
    tomcat7
    {%- elif (
        ansible_distribution.lower() in ['ubuntu'] and
        ansible_distribution_version|copsf_looseversion <=
          '16.04'|copsf_looseversion) -%}
    tomcat7
    {%- else -%}
    tomcat8
    {%- endif -%}"
geoserver_jce_headers:
  Cookie:oraclelicense=accept-securebackup-cookie
geoserver_jce: "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"
geoserver_java_home: "/usr/lib/jvm/java-8-oracle"
geoserver_archive: "https://downloads.sourceforge.net/project/geoserver/GeoServer/{{vars['geoserver_version']}}/geoserver-{{vars['geoserver_version']}}-war.zip"
geoserver_tomcat_vpath: "{{geoserver_proot}}/apache-tomcat-{{geoserver_name}}-{{geoserver_tomcat_ver}}"
geoserver_tomcat_path: "{{geoserver_proot}}/apache-tomcat-{{geoserver_name}}"
geoserver_tomcat_loglnk: "/var/log/tomcat-{{geoserver_name}}"
geoserver_tomcat_deactivated_apps: [examples, doc, docs, "host-manager", manager]
geoserver_tomcat_bin:
- filetest: [conf, webapps]
  app_path: "{{vars['geoserver_tomcat_vpath']}}"
  urls:
    archive: "http://apache.mirrors.ovh.net/ftp.apache.org/dist/tomcat/tomcat-8/v{{geoserver_tomcat_ver}}/bin/apache-tomcat-{{geoserver_tomcat_ver}}.tar.gz"
    checksum: "{{geoserver_tomcat_sha}}"
    verify_sha256: true
geoserver_archives:
- filetest: []
  app_path: "{{vars['geoserver_root']}}"
  urls:
    archive: "{{geoserver_archive}}"
    archive_crc: "{{geoserver_sha}}"
    verify_sha256: true
geoserver_root: "{{vars['geoserver_proot']}}/geoserver-{{vars['geoserver_version']}}"
geoserver_plugin_archives:
- filetest: []
  app_path: "{{vars['geoserver_root']}}"
  urls:
    archive: "https://downloads.sourceforge.net/project/geoserver/GeoServer/{{vars['geoserver_version']}}/extensions/geoserver-{{vars['geoserver_version']}}-pyramid-plugin.zip"
    archive_crc: "{{geoserver_plugin_pyramid_sha}}"
    verify_sha256: true
- filetest: []
  app_path: "{{vars['geoserver_root']}}"
  urls:
    archive: "https://downloads.sourceforge.net/project/geoserver/GeoServer/{{vars['geoserver_version']}}/extensions/geoserver-{{vars['geoserver_version']}}-gdal-plugin.zip"
    archive_crc: "{{geoserver_plugin_gdal_sha}}"
    verify_sha256: true
geoserver_gdal_data: /usr/share/gdal/2.2
geoserver_jai:
- filetest: [lib/jai_core.jar]
  app_path: "{{vars['geoserver_proot']}}/jai"
  urls:
    archive: "https://github.com/corpusops/corpusops.bootstrap/releases/download/files/jai-1_1_3-lib-linux-amd64.tar.gz"
    archive_crc: "https://github.com/corpusops/corpusops.bootstrap/releases/download/files/jai.shas"
    verify_sha256: true
- filetest: [lib/jai_imageio.jar]
  app_path: "{{vars['geoserver_proot']}}/jai"
  urls:
    archive: "https://github.com/corpusops/corpusops.bootstrap/releases/download/files/jai_imageio-1_1-lib-linux-amd64.tar.gz"
    archive_crc: "https://github.com/corpusops/corpusops.bootstrap/releases/download/files/jai.shas"
    verify_sha256: true
geoserver_domain: "{{ansible_fqdn}}"
geoserver_nginx_basename: "corpusops-{{vars['geoserver_name']}}"
geoserver_nginx_upstream_name: "corpusops{{vars['geoserver_name']}}"
geoserver_nginx_domain: "{{vars['geoserver_domain']}}"
geoserver_nginx_server_aliases: ["www.{{vars['geoserver_domain']}}"]
geoserver_nginx_redirect_aliases: false
geoserver_nginx_port: "80"
geoserver_nginx_ssl_port: "443"
geoserver_nginx_content_template: "../templates/geoserver.conf"
geoserver_nginx_top_template: "../templates/geoserver.top.conf"
geoserver_nginx_is_default_server: true
geoserver_nginx_htpasswd: "{{vars['geoserver_htpasswd']}}"
geoserver_nginx_ssl_protected: false
geoserver_nginx_ssl_cert: ""
geoserver_nginx_ssl_key: ""
geoserver_nginx_loglevel: crit
geoserver_nginx_doc_root: "/var/www"
geoserver_force_ssl: true
geoserver_host: localhost
geoserver_address: 127.0.0.1
geoserver_port: 8080
geoserver_sport: 8443
geoserver_htpasswd: /etc/nginx/geoserver.htpasswd
geoserver_http_users: []
geoserver_default_vhost_is_default_server: false
geoserver_tomcat_roles:
- name: tomcat
geoserver_tomcat_users:
- username: admin
  password: secret8p646D6UfvmhGUschanged
  roles: [tomcat]
geoserver_tomcat_service: "tomcat-{{vars['geoserver_name']}}"
geoserver_nofile: 49152
