#!/usr/bin/env bash

# {{ ansible_managed}}

if [ "x${LD_LIBRARY_PATH-}" != "x" ];then
    export LD_LIBRARY_PATH=":${LD_LIBRARY_PATH}"
fi
export LD_LIBRARY_PATH="/usr/lib/jni${LD_LIBRARY_PATH}"

GDAL_DATA="{{_geoserver_gdal.stdout.strip()}}"
GEOSERVER_HOME="{{geoserver_vars.home}}"
GEOSERVER_DATA_DIR="{{geoserver_vars.data}}"

# Run Tomcat as this user ID. Not setting this or leaving it blank will use the
# default of tomcat8.
TOMCAT8_USER="{{geoserver_vars.tomcat}}"

# Run Tomcat as this group ID. Not setting this or leaving it blank will use
# the default of tomcat8.
TOMCAT8_GROUP="{{geoserver_vars.tomcat}}"

# The home directory of the Java development kit (JDK). You need at least
# JDK version 8. If JAVA_HOME is not set, some common directories for
# OpenJDK and the Oracle JDK are tried.
JAVA_HOME="{{geoserver_vars.java_home}}"

# You may pass JVM startup parameters to Java here. If unset, the default
# options will be: -Djava.awt.headless=true -XX:+UseConcMarkSweepGC
#
# Use "-XX:+UseConcMarkSweepGC" to enable the CMS garbage collector (improved
# response time). If you use that option and you run Tomcat on a machine with
# exactly one CPU chip that contains one or two cores, you should also add
# the "-XX:+CMSIncrementalMode" option.
JAVA_OPTS="{{geoserver_vars.java_opts.strip()}}"
CATALINA_OPTS="$JAVA_OPTS"

# To enable remote debugging uncomment the following line.
# You will then be able to use a java debugger on port 8000.
#JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"

# Java compiler to use for translating JavaServer Pages (JSPs). You can use all
# compilers that are accepted by Ant's build.compiler property.
#JSP_COMPILER=javac

# Use the Java security manager? (yes/no, default: no)
#TOMCAT8_SECURITY=no

# Number of days to keep logfiles in /var/log/tomcat8. Default is 14 days.
#LOGFILE_DAYS=14
# Whether to compress logfiles older than today's
#LOGFILE_COMPRESS=1

# Location of the JVM temporary directory
# WARNING: This directory will be destroyed and recreated at every startup !
#JVM_TMP=/tmp/tomcat8-temp

# If you run Tomcat on port numbers that are all higher than 1023, then you
# do not need authbind.  It is used for binding Tomcat to lower port numbers.
# (yes/no, default: no)
#AUTHBIND=no
export TOMCAT8_GROUP TOMCAT8_USER
export GDAL_DATA
export GEOSERVER_HOME GEOSERVER_DATA_DIR
export JAVA_OPTS JAVA_HOME CATALINA_OPTS
